.gitmodules
gulpfile.js
package.json
src/template/index.jade

This PR adds MCProHosting/beam-client-java as a git submodule in order to generate docs.
The docs are generated via a gulp task, and then are piped into a static directory to serve on the site.

Add docs for beam-client-java to site

---

src/api/docs/achievements/achievementMethod.js
src/api/docs/channel/follow.js

Typo fixes for "preform" to "perform in 403 errors.

---

src/_html/oauth.html

- channel:details:self dose not include the streamkey anymore.

Update on scope.

---

build/misc.js

require caches the result, we don't want that here.

do not cache raml json

---

src/reference/chat/data.json

Server replies with `"authenticated": false`, not `true`.

Fix anonymous authentication response

---

build/docs.js
build/misc.js
build/util.js
src/rest/resource.pug
src/rest/template.pug

Caveats: This pulls the data from `default.js` which shouldn't make a different right now but might later, sadly `config` does not allow being instantiated with different working directories.
Pro: Automatic rate limit table building, YAY!
@connor4312 If you have a minute it would be totally cool if you could add a little `database` or `cache` icon to the endpoints (like the `lock` icon for secured endpoints), I didn't really understand how your glyph icon font thingy works 😛 
Requires: https://github.com/WatchBeam/backend/pull/859 to be merged to master to work correctly.

Added rate limiting table and displaying for endpoints

---

src/tutorials/code/python/chat/1.py
src/tutorials/code/python/chat/5.py

The Python section for the basic chat bot tutorial gives the code inside the config file as being lowercase, which won't work with the rest of the code/the framework. Later on in the code, `config.CHANNEL` is requested, which would always error because channel is lowercase in the config.
Additionally, all values required by [beam-client-python](https://github.com/WatchBeam/beam-client-python) are uppercase too, causing problems later on down the line. This PR converts the config variables in the tutorial to uppercase.

FIx broken Python code in chat bot tutorial

---

src/reference/chat/data.json

A bot dev was unaware this was the case and had a chat message fire on this event.
Led to some spam.
Should really be PollProgress for progress or something but we can look at that once the docs are correct.

Correct pollstart docs

---

src/reference/chat/data.json

The documentation for `ChatMessage`s was incorrect, for emotes especially.
Note: `vote:start` and `WelcomeEvent` were only "updated" due to (automatic) indentation formatting. No content was changed.

Fix ChatMessage packet documentation

---

src/rest/resource.pug

This lets us deprecate security schemes and display them nicely:
Its paired with another PR for backend shortly

Support deprecated security schemes

---

build/docs.js
package.json
src/rest/template.pug
src/rest/type.pug
src/tutorials/code/node/interactive/2.js
src/tutorials/code/node/interactive/5.js

Simplified some logic by making the internal annotation universally filterable.
Reduced some functions pointlessly returning input values.
Updated some function docs.
Fixed item rendering for array types.
Moved some display logic (ordered objects) into the views.
Fixes: #130

filter all nodes by internal annotation, cleanup, fix simple typed array items not being rendered

---

src/reference/oauth/index.pug

Adds an explanation of how shortcode works to the OAuth reference page. Tried to keep this as short and concise as possible, referencing the REST API docs where possible for more info.

Add a short summary of how shortcode OAuth works

---

config/default.yaml
gulpfile.js

I keep doing things similar to this locally it would be great to move it to config so that i dont keep having to accidentally check in a manual disable for it.

Add a config option to control java doc creation

---

LICENSE
readme.md
src/css/_footer.less
src/index.pug
src/layout.pug
src/reference/chat/data.json
src/reference/chat/index.pug
src/reference/interactive1/index.pug
src/reference/interactive1/protocol.pug
src/reference/oauth/index.pug
src/tutorials/channelid.pug
src/tutorials/chatbot.pug
src/tutorials/constellation.pug
src/tutorials/interactive.pug
src/tutorials/rest.pug

* Changed Twitter and Facebook links from /Mixer to /WatchMixer.
* Replace the v1 "Interactive Lab" button in the navigation bar with links to "Interactive Studio" and "OAuth Apps".
* Definitely open to feedback on this one in particular. I think it makes sense to put direct links to the new studio in the navbar, particularly because the legacy lab is already linked to from the v2 studio, in the v1 docs, and on the main site's navbar.
* Replace any links for OAuth with a direct link to /lab/oauth.
* Fix broken About link in the footer.
* Fix Mixer logo overflowing outside of the footer.
* https'ify forums link.
* Add link to feedback in the footer.
* Update license copyright.
* Fix a few instances where we still said Beam, not Mixer.
* Made a quick pass over some of the pages and fixed …

Minor adjustments and corrections post-rebrand

---

src/reference/chat/data.json

- Also made a note about the object not being defined when the event is trigged from a ban and not an actual moderator timing a user out.

Added: Moderator object to the PurgeMessage event.

---

src/reference/oauth/index.pug

Added a sentence to the OAuth reference page to clarify we allow you to set `approval_prompt=force` to prevent automatic reauthorization.

Add documentation for approval_prompt=force

---

src/reference/constellation/events.json
src/reference/constellation/index.pug
src/rest/type.pug

Adds info on each Constellation event's payload/fields, as well as full examples for each. Also adds `costream:{id}:update`.

feat(constellation): add documentation for events

---

src/reference/chat/data.json
src/reference/chat/index.pug
src/reference/chat/menu.pug

Made some minor changes to the chat reference:
* Separated out each chat method's arguments and required permissions, and then added them to methods that didn't have any docs there before.
* Clarified timeout duration & how giveaways work.
* Fixed a couple of incorrect method names.
* Added missing `originatingChannel` to poll events.
* Fixed links for methods with a colon.

feat(chat): clarify chat reference

---

build/docs.js

Quick idea I had. Lets us hit the "deploy" button on the dev site to have endpoints magically appear when they're released instead of needing to branch, edit, PR, and review removing `(internal)` tags on the backend, then deploying the dev site. E.g. with costreams they didn't actually make it onto the dev site for a couple weeks after release.

feat(doc-gen): allow endpoints to be hidden until embargo dates pass

---

src/rest/resource.pug

(announce): can now be used to designate an announcement, displayed at the top of the endpoint modal as a yellow warning bootstrap alert.

feat(layout): Add announce annotation

---

package.json

New version is 5.0.5, see [linked PR](https://github.com/mixer/common/pull/68).

fix(docs): Change channel:analytics, bumping common ver

---

src/reference/interactive/protocol/protocol.rst

Adds docs to the protocol doc for `keydown` and `keyup` input events.
Also fixed `mousedown`'s indentation, and removed `transactionId` from `mouseup` and `move` events since I don't think they can have a transaction(?).

feat(protocol): add keydown and keyup input events

---

src/reference/interactive/protocol/protocol.rst

Adds `tooltip` to the protocol doc

feat(protocol): add tooltip property to button

---

build/libraries.json
src/rest/type.pug

Here we update the union handling to be a bit better. A lot of this was a bit of a mess.The array handling was clobbering unions.
In addition unions in raml are without "()" [spec](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#union-type)
The raml updates to make this render correctly are in: https://github.com/mixer/backend/pull/1464

fix(unions): Make unions render correctly when arrays are involved

---

src/tutorials/chatbot.pug

The `Click here to get your token` link in all the tutorials automatically gives you an access token for making a simple ping/pong bot. However, a few have had trouble with this because the bot runs under the same account as the developer. The chat server sees "!ping" then "PONG!" from the same user, and then "PONG!" is blocked due to slowchat.
This adds `chat:bypass_slowchat` to the access token link to fix this problem, for those who want to get started making a chat bot.
Bug 3903

fix(tutorial): add chat:bypass_slowchat scope to token link

---

src/reference/interactive/protocol/protocol.rst

Offsetting codes are fun. Correct the codes in the protocol.rst by referring to the table.

docs(protocol): Correct some offsets in Server Interaction

---

build/misc.js
package.json

The OAuth Scopes table won't generate if beam-common isn't available, so third-parties can still build the site.

fix(build): make beam-common an optional dep

---

src/reference/constellation/events.json

Removes the weird `channel:{id}:status` (`chat:{id}:StartStreaming`) event from the constellation reference, in favour of just listening to `channel:{id}:update`.

fix(constellation): remove status event

---

src/index.pug
src/layout.pug

Replaces forums.mixer.com links with links to our Discord server, for now

fix: replace forums links

---

src/reference/chat/data.json

If a chatbot is a mod, they might want to properly handle/ignore Catbot-filtered messages. Added an example to the chat reference to explain this.

feat(chat): add documentation for catbot

---

src/reference/interactive/index.pug

Every other SDK opens in a new tab, why not Unity  ¯\_(ツ)_/¯

Open Unity SDK in a new tab

---

src/rest/type.pug

When trying to run `gulp recompile` the following error happened:
```
PS D:\developers> npm run rebuild
> beam-developers@2.0.0 rebuild D:\developers
> gulp recompile
[22:20:20] Using gulpfile D:\developers\gulpfile.js
[22:20:20] Starting 'html-quick'...
Cannot find common module. OAuth scope table will be omitted.
[22:20:20] Starting 'js'...
[22:20:20] Starting 'iconfont'...
[22:20:20] Starting 'images'...
[22:20:21] gulp-svgicons2svgfont: The fontHeight should larger than 1000 or it will be converted into the wrong shape. Using the "normalize" and "fontHeight" options can solve the problem.
[22:20:21] gulp-svgicons2svgfont: Font created
[22:20:21] Finished 'js' after 629 ms
[22:20:21] Finished 'iconfont' after 884 ms
[22:20:21] Starting 'css'...
[22:20:22] Finished 'css' after 1.06 s …
```

Fix rebuild for outside developers

---

src/reference/interactive_next/game-clients.pug

Minor Documentation Fixes:
- Typo in method call
- Clarifies arguments to updateParticipants
- Sample is no longer written in typescript

fix(game-clients): Fix typo and clarify

---

src/reference/interactive_next/controls/scene-01.jsx

Mixer.Scene uses id, not name.
PreactScene requires at least one type argument, added empty object to replicate default scene
super.render doesn't work because PreactScene doesn't implement it and it's ancestor is abstract.

fix(next-preact): fix some tutorial code issues
