mixer/developers

- .gitmodules
- gulpfile.js
- package.json
- src/template/index.jade
Reverts MCProHosting/beam-developers#3
> Revert "Add docs for beam-client-java to site"

- src/api/docs/user/followingChannels.js
And basing it off of the correct branch, this time >_<
> Updating docs to show new ordering of follows endpoint

- src/api/docs/user/findPreferences.js
Adding the "channel:mature:allowed" preference to the successful example. Probably don't want to merge this until the backend changes have been merged.
> Updating findPreferences successful example

- src/api/docs/channel/listTypes.js
Sync with changes made in https://github.com/WatchBeam/backend/pull/39
> Update type documentation

- README.md
- src/api/docs/achievements/achievementMethod.js
- src/api/docs/achievements/findAll.js
- src/api/docs/achievements/userFind.js
- src/api/docs/channel/follow.js
- src/api/docs/channel/follows.js
- src/api/docs/channel/listTypes.js
- src/api/docs/channel/types.js
- src/api/docs/channel/updateUserRole.js
- src/api/docs/channel/userRoles.js
- src/api/docs/chat/findArchived.js
- src/api/docs/chat/findOne.js
- src/api/docs/chat/updateSettings.js
- src/api/docs/chat/userList.js
- src/api/docs/chat/userSearch.js
- src/api/docs/liveloading/subscribe.js
- src/api/docs/liveloading/unsubscribe.js
- src/api/method.js
- src/api/orderParameter.js
- src/api/parameter.js
- Fixed: Various spelling mistakes and a few URI's being wrong (Extra forward slashes which were not needed)
- Fixed: Some formatting on the descriptions and added spaces where appropriate.
- Updated: Endpoint responses (examples) As they were severely outdated and some developers were getting confused on what data we meant to be returned.
- Changed: Removed some parameters which are not used for the endpoint and tweaked some wording on the descriptions.
- Achievements:
- All: http://i.imgur.com/LkcdQgu.png
- User: http://i.imgur.com/daF20A6.png
- Chats:
- Get: http://i.imgur.com/GijSq43.png
I can get more screenshots if you want of the other things I've changed / fixed but I gave some examples so you can see the changes ^_^ I will go over the rest of the endpoints when I get more spare …
> Misc - Changes / Fixes

- src/server/index.js
> Sync is bad and you should feel bad

- package.json
Fixed The Mcprohosting To WatchBeam
> Fixed The Mcprohosting To WatchBeam

- src/_html/chatproto.html
2 months ago there was a change to the message property on chat messages. Thought i'd help you out by writing up the change.
> Update ChatProto Documentation Fixes #59

- src/components/oauth_manage.jsx
This goes along with https://github.com/WatchBeam/backend/pull/376. Just needs some camel casing of properties here.
> Update property names with new OAuth API

- README.md
- package.json
> fixed beam client node and added link to dev site 

- src/api/docs/achievements/achievementMethod.js
- src/api/docs/achievements/findAll.js
- src/api/docs/achievements/userFind.js
- src/api/docs/channel/createThumbnail.js
- src/api/docs/channel/findOne.js
- src/api/docs/channel/follow.js
- src/api/docs/channel/follows.js
- src/api/docs/channel/listTypes.js
- src/api/docs/channel/successfulResponse.js
- src/api/docs/chat/clearChat.js
- src/api/docs/chat/findArchived.js
- src/api/docs/resource/findAll.js
- src/api/docs/resource/findOne.js
- src/api/docs/user/expandedSuccessfulExample.js
- src/api/docs/user/findPreferences.js
- Will update the rest soon and maybe also create some docs for live loading with example data etc..
> Updated a few common endpoints. (Channels / Users)

- src/api/docs/channel/successfulResponse.js
> updated stuff 

- src/_html/oauth.html
It took me some searching to find these in the gitter.
> Add tetris scopes

- src/api/docs/channel/successfulResponse.js
- Also updated the experience to match the level.
> Added - Level to the user object. (Channels endpoint)

- src/tutorials/code/python/interactive/3.py
- src/tutorials/code/python/interactive/4.py
- src/tutorials/code/python/interactive/5.py
Just a small change that will hopefully remove a bit of confusion.
> Remove unnecessary `connection` argument from handlers

- .pug-lintrc
- src/mixins.pug
> Fixed lint, added required src

- build/docs.js
@Doridian You'll need to wipe the build/tmp folder once for this to work.
> use master branch for backend pull

- src/rest/resource.pug
> Show deprecation status if present

- src/reference/chat/data.json
- make indentation consistent
- fix typos
- fix link text
> Fix formatting

- src/layout.pug
- src/legal/attributions.pug
- src/legal/licenses.txt
> Add licensing/attribution list

- src/css/_rest.less
- src/icons/minus-5.svg
- src/icons/time-1.svg
- src/rest/resource.pug
> Rate limiting and deprecated icons

- src/rest/csrf.txt
- src/rest/template.pug
Tried to keep it brief but verbose enought to explain everything
> Add csrf explanation

- src/tutorials/code/python/chat/2.py
- src/tutorials/code/python/chat/4.py
- src/tutorials/code/python/chat/5.py
> Clarify on-message functionality in Python chat tutorial

- .gitignore
- build/misc.js
- package.json
- src/reference/chat/data.json
- src/rest/resource.pug
You can ignore most of the json diff, that was just linting
> Add attachEmotes method + cleanup

- build/misc.js
- src/rest/resource.pug
Mostly to support /users/current docs:
> Clarify/fix OAuth Documentation

- build/docs.js
- config/.gitignore
- config/default.yaml
Just a couple things I ran into building the site on a new machine
> Add repo example to config, ignore local configs, fix maven build failure

- build/docs.js
- package.json
- readme.md
There was some weirdness going on with the patching on raml objects, we should rewrite this in TS entirely, but for now this makes sure we don't leak internal docs anymore.
> fixed (internal) not working sometimes

- src/reference/chat/data.json
- src/reference/chat/index.pug
- src/reference/chat/menu.pug
It turns out that UNOTFOUND is very unhelpful, I've added a troubleshooting guide for how to handle that in the efforts it might help save the 40 minutes it usually takes to figure this one out.
> Add some troubleshooting data to the chat reference

- src/rest/type.pug
> Add support for RAML union types in model docs

- src/tutorials/code/node/interactive/2.js
- src/tutorials/code/node/interactive/5.js
the variable "client" is never actually introduced, should be "beam".
> Fix error using 'client' instead of 'beam'

- src/reference/oauth/index.pug
> corrected link

- src/reference/chat/data.json
> updated UserJoin and UserLeave docs

- build/docs.js
> fixed concurrent modification related error

- src/reference/interactive/protocol/protocol.rst
The paths for the object were a little off, corrected those.
> Fix incorrect paths

- src/reference/interactive/cplusplus/data.json
- src/reference/interactive/csharp/data.json
update Unity and C++ API ref docs from beam to mixer
> Beam to Mixer

- src/reference/constellation/events.json
I'm feeling bad about this one! Someone asked about this.
Changes `followed` to `following`.
> fix(constellation): correct "following" property

- build/docs.js
- config/default.yaml
- gulpfile.js
- readme.md
As these are now built into Gh-pages we don't need them here.
> chore(build): Remove mvn building as this happens elsewhere now

- build/docs.js
- package.json
- src/reference/chat/data.json
- src/reference/constellation/events.json
- src/reference/interactive/index.pug
- src/reference/interactive1/proto/tetris.proto
This gets all the safe references, there are some in our tutorials but these need a pass especially when it comes to java. I'll get Pahimar to followup there as he did the rename operation on the actual repo
> chore(*): Remove some references to beam

- build/misc.js
> chore(build): warn when common is missing

- src/layout.pug
- src/reference/interactive/index.pug
Updates a few links after Interactive Studio + OAuth Apps were combined.
> feat(interactive): update links for developer lab

- src/reference/chat/data.json
Noticed the `ChatMessage` data was double-wrapped. Also added a couple of missing fields.
> fix(chat): minor chat reference corrections

- src/tutorials/chatbot.pug
- src/tutorials/code/node/chatbot/1.js
- src/tutorials/code/node/chatbot/2.js
- src/tutorials/code/node/chatbot/3.js
Updated the chat tutorial to work with the TypeScript port of beam-client-node (1.x.x). Also made a quick spelling/grammar pass over the tutorial.
> feat(chat): update chat tutorial for beam-client-node 1.0.0

- src/tutorials/code/node/chatbot/1.js
- src/tutorials/code/node/chatbot/2.js
- src/tutorials/code/node/chatbot/3.js
> fix(chat): fix some minor issues with examples

- src/index.pug
addresses https://github.com/mixer/developers/pull/194#discussion_r164902446
> style(home): remove extraneous image attribute

- src/index.pug
- src/layout.pug
I've received far too many emails asking about interactive 1.
Direct links and saved bookmarks will still work
> feat(*): pull out top level links to interactive 1 to avoid confusion

- src/css/_type.less
- src/layout.pug
- src/reference/constellation/events.json
- src/reference/constellation/events_table.pug
- src/reference/constellation/index.pug
- src/reference/oauth/index.pug
- src/reference/webhooks/curl_request.sh
- src/reference/webhooks/example_full_request.txt
- src/reference/webhooks/example_hook.json
- src/reference/webhooks/index.pug
- src/reference/webhooks/verify.cs
- src/reference/webhooks/verify.go
- src/reference/webhooks/verify.js.txt
- src/reference/webhooks/verify.php
- src/reference/webhooks/verify.py
- src/rest/resource.pug
Should be mostly complete, feel free to leave comments or just push up any corrections/additions you may have :)
> feat: add webhook reference doc

- src/css/_rest.less
- src/index.pug
- src/reference/interactive/index.pug
- src/reference/interactive/menu.pug
- src/reference/reference_layout.pug
- src/rest/template.pug
This does a couple of things, we'll squash merge
- Moves most sidebars to the left. Design told me to do this :)
- Expands the interactive sidebar by default. I had some feedback that the hidden state was confusing
- Moves around a couple of sections to a better pattern
- Adds the word game a couple of places
- Aka.ms'es some external getting started links. I want to share these out but I know the links will change soon aka.ms was made for this :P
> Refactor 1

- src/reference/interactive/index.pug
- src/reference/interactive/menu.pug
These docs are really really basic, I feel bad that they are this small but they're a start from here we can only write more and keep them up to date. The very fact we ask people to contact us is great.
> feat(interactive): basic scale docs

- src/layout.pug
- src/legal/developer-agreement.pug
Add the Mixer developer agreement full text as a new page in the legal section.
> feat(dev-agreement): Add the developer agreement

- src/tutorials/code/raw/chat/1.sh
- src/tutorials/code/raw/chat/2.sh
> fix(chat): fix chat curl tutorial

- src/reference/constellation/events.json
Will push after https://github.com/mixer/backend/pull/2034 goes in
> feat(update): updating direct purchase constellation doc

- src/tutorials/chatbot.pug
- src/tutorials/code/node/chatbot/1.js
- src/tutorials/code/node/chatbot/2.js
- src/tutorials/code/node/chatbot/3.js
- src/tutorials/code/node/interactive/1.js
- src/tutorials/code/node/interactive/5.js
- src/tutorials/code/node/rest/1.js
- src/tutorials/code/node/rest/2.js
- src/tutorials/code/node/rest/5.js
- src/tutorials/interactive.pug
- src/tutorials/rest.pug
Depends on https://github.com/mixer/client-node being published first.
> [do not merge] feat(tutorials): rename node library
